### PR TITLE
Hook up email_order -> sales_order FK relationship in split db mode

### PR DESCRIPTION
**Pull request by simon-letch**
As discussed, this is slightly academic as you can't delete orders through default Magneto UI.

But, it's a small change and will satisfy Magento architect's review.

I'm keen to hear your thoughts.

### CODE REVIEW

**Comment by adeelq** [comment]
Agree gonna run this. I guess only way to trigger this or make sure it works is to remove order by code.

**Comment by adeelq** [comment]
Not making any difference in split mode when removing Magento order it does not remove order from email_order table. I remove foreign key relation from mysql table to test this properly.

**Comment by simon-letch** [comment]
Can you breakpoint the Magento\Framework\ForeignKey\ObjectRelationProcessor\Plugin? If that doesn't get hit, then that's the problem. The whole FK framework relies on that plugin firing to cascade deletes. I was using a Raveinfosys Deleteorder extension to delete orders.

**Comment by adeelq** [comment]
Did this change worked for you? I'm using https://github.com/mageplaza/magento-2-delete-orders to delete orders and did not work for me. I can try your one if it worked for you

**Comment by adeelq** [comment]
Raveinfosys Deleteorder is not removing order. i guess it is not compatible with split db. Did you test this in split db using this extension? can you give me link to extension if it does remove order.

**Comment by simon-letch** [comment]
Replace removeById method in Remove.php with

**Comment by cdiacon** [comment]
same here - hitting the plugin but not getting any constraints that will be resolved for foreign key so the order data is not removed from "email_order" but removed from "sales_order"

**Comment by simon-letch** [comment]
Ok, i'm just working on install scripts in split db, then i'll be able to re-run this.

The plugin should pick up that data is being deleted from sales_order. Then query constraints for any referenceEntity sales_order, returning the new one i've created in constraints.xml.

**Comment by adeelq** [comment]
this time plugin hit with following exception 

1 exception(s):
Exception #0 (Magento\Framework\Exception\LocalizedException): Unknown field name: entity_id

Exception #0 (Magento\Framework\Exception\LocalizedException): Unknown field name: entity_id
#0 /Users/adeelqamar/Sites/Magento-EE-2.2.5_sample_data-2018-06-26-10-29-38/vendor/magento/framework-foreign-key/ConstraintProcessor.php(48): Magento\Framework\ForeignKey\ConstraintProcessor->getInvolvedData(Array, 'entity_id')
#1 /Users/adeelqamar/Sites/Magento-EE-2.2.5_sample_data-2018-06-26-10-29-38/vendor/magento/framework-foreign-key/ObjectRelationProcessor/Plugin.php(79): Magento\Framework\ForeignKey\ConstraintProcessor->resolve(Object(Magento\Framework\Model\ResourceModel\Db\TransactionManager), Object(Magento\Framework\ForeignKey\Constraint), Array)
#2 /Users/adeelqamar/Sites/Magento-EE-2.2.5_sample_data-2018-06-26-10-29-38/vendor/magento/framework/Interception/Interceptor.php(121): Magento\Framework\ForeignKey\ObjectRelationProcessor\Plugin->beforeDelete(Object(Magento\Framework\Model\ResourceModel\Db\ObjectRelationProcessor\Interceptor), Object(Magento\Framework\Model\ResourceModel\Db\TransactionManager), Object(Magento\Framework\DB\Adapter\Pdo\Mysql), 'sales_order', 'entity_id=''', Array)
#3 /Users/adeelqamar/Sites/Magento-EE-2.2.5_sample_data-2018-06-26-10-29-38/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\Model\ResourceModel\Db\ObjectRelationProcessor\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\Model\ResourceModel\Db\TransactionManager), Object(Magento\Framework\DB\Adapter\Pdo\Mysql), 'sales_order', 'entity_id=''', Array)
#4 /Users/adeelqamar/Sites/Magento-EE-2.2.5_sample_data-2018-06-26-10-29-38/generated/code/Magento/Framework/Model/ResourceModel/Db/ObjectRelationProcessor/Interceptor.php(25): Magento\Framework\Model\ResourceModel\Db\ObjectRelationProcessor\Interceptor->___callPlugins('delete', Array, Array)
#5 /Users/adeelqamar/Sites/Magento-EE-2.2.5_sample_data-2018-06-26-10-29-38/vendor/magento/framework/Model/ResourceModel/Db/AbstractDb.php(452): Magento\Framework\Model\ResourceModel\Db\ObjectRelationProcessor\Interceptor->delete(Object(Magento\Framework\Model\ResourceModel\Db\TransactionManager), Object(Magento\Framework\DB\Adapter\Pdo\Mysql), 'sales_order', 'entity_id=''', Array)
#6 /Users/adeelqamar/Sites/Magento-EE-2.2.5_sample_data-2018-06-26-10-29-38/generated/code/Magento/Sales/Model/ResourceModel/Order/Interceptor.php(128): Magento\Framework\Model\ResourceModel\Db\AbstractDb->delete(Object(Magento\Sales\Model\Order\Interceptor))

**Comment by adeelq** [comment]
However it did remove the order from email_orders :)

**Comment by adeelq** [comment]
now keep getting above exception. order is not removed.

**Comment by simon-letch** [comment]
can you reset your sample data and try again?

bin/magento sampledata:reset
bin/magento setup:upgrade

**Comment by adeelq** [comment]
OK working now as expected +1

**Pull request merged**
